Update weapons and Vehicle to implement military flashlight attachment
DayZMod/DayZ pull request #800
Opened 2016-12-20 18:32 UTC by Streatman

2016-12-25 17:57 UTC, ebayShopper requested changes

2016-12-25 17:57 UTC, ebayShopper commented on SQF/dayz_code/stringtable.xml
>  		</Key>
@Streatman - You accidentally duplicated a ton of strings that were already in the stringtable.

2016-12-28 16:04 UTC, Streatman reviewed
i fixed the stringtables and added the remington that i forgot

2016-12-28 16:04 UTC, Streatman commented on SQF/dayz_code/stringtable.xml
>  		</Key>
oh.... oups

2017-01-07 22:22 UTC, ebayShopper commented on SQF/dayz_code/stringtable.xml
> +		<Key ID="STR_DZ_ATT_FL_PST_DESC">
Typo here, this should be `STR_DZ_ATT_MFL_PST_DESC`

2017-01-08 11:37 UTC, Streatman commented on SQF/dayz_code/stringtable.xml
> +		<Key ID="STR_DZ_ATT_FL_PST_DESC">
fixed

2017-01-09 02:19 UTC, merged